# Generated by Django 4.2.14 on 2024-07-28 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Weather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_date", models.CharField(max_length=8)),
                ("fcst_date", models.CharField(max_length=8)),
                ("base_time", models.CharField(max_length=4)),
                ("POP", models.IntegerField(null=True)),
                ("TMX", models.IntegerField(null=True)),
                ("TMN", models.IntegerField(null=True)),
                ("SKY", models.IntegerField(null=True)),
                ("fcst_value", models.CharField(max_length=10)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.location",
                    ),
                ),
            ],
            options={
                "unique_together": {("location", "fcst_date", "base_time")},
            },
        ),
    ]
