# Generated by Django 4.2.14 on 2024-07-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weather",
            name="fcst_value",
        ),
    ]
