# Generated by Django 4.2.14 on 2024-07-23 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Weather",
        ),
    ]
