# Generated by Django 4.2.14 on 2024-07-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0002_remove_weather_fcst_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weather",
            name="POP",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="weather",
            name="SKY",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="weather",
            name="TMN",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="weather",
            name="TMX",
            field=models.FloatField(null=True),
        ),
    ]
