# Generated by Django 4.2.14 on 2024-07-24 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        ("weather", "0002_delete_weather"),
    ]

    operations = [
        migrations.CreateModel(
            name="Weather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_date", models.DateField()),
                ("base_time", models.TimeField()),
                ("fcst_date", models.DateField()),
                ("category", models.CharField(max_length=10)),
                ("fcst_value", models.CharField(max_length=20)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_set",
                        to="locations.location",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["location", "fcst_date"],
                        name="weather_wea_locatio_0ec979_idx",
                    )
                ],
                "unique_together": {
                    ("location", "base_date", "base_time", "fcst_date", "category")
                },
            },
        ),
    ]
