# Generated by Django 4.2.14 on 2024-07-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0003_alter_weather_pop_alter_weather_sky_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weather",
            name="SKY",
            field=models.IntegerField(null=True),
        ),
    ]
