# Generated by Django 4.2.14 on 2024-07-28 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0004_alter_weather_sky"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weather",
            old_name="TMN",
            new_name="TMP",
        ),
        migrations.RemoveField(
            model_name="weather",
            name="TMX",
        ),
    ]
