# Generated by Django 4.2.14 on 2024-07-26 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("weather", "0004_rename_category_weather_w_category_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="weather",
            name="weather_wea_locatio_0ec979_idx",
        ),
        migrations.AlterUniqueTogether(
            name="weather",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="weather",
            name="POP",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="weather",
            name="SKY",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="weather",
            name="TMN",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="weather",
            name="TMX",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="weather",
            name="base_date",
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name="weather",
            name="base_time",
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name="weather",
            name="fcst_date",
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name="weather",
            name="fcst_value",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="weather",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="locations.location"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="weather",
            unique_together={("location", "fcst_date", "base_time")},
        ),
        migrations.RemoveField(
            model_name="weather",
            name="W_category",
        ),
    ]
