# Generated by Django 4.2.14 on 2024-07-28 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0005_rename_tmn_weather_tmp_remove_weather_tmx"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weather",
            old_name="TMP",
            new_name="T1H",
        ),
    ]
