# Generated by Django 4.2.14 on 2024-07-28 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0006_rename_tmp_weather_t1h"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weather",
            old_name="T1H",
            new_name="TMP",
        ),
    ]
