# Generated by Django 4.2.14 on 2024-07-28 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0007_rename_t1h_weather_tmp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weather",
            old_name="TMP",
            new_name="T1H",
        ),
    ]
