 #version: "3.11"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./han_cycle:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  celery_worker:  # Celery worker 서비스 추가
    build: .
    command: celery -A han_cycle worker -l info
    env_file:
      - .env
    depends_on:
      - redis
      - db

  celery_beat:  # Celery beat 서비스 추가(자동화 API요청_날씨)
    build: .
    command: celery -A han_cycle beat -l info
    env_file:
      - .env
    depends_on:
      - redis
      - db
      
  redis:
    image: redis:alpine      #celery 브로커

volumes:
  postgres_data:
