#version: "3.11"
services:
  app: 
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./han_cycle:/apㅔ
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      - db
      - redis
      - elasticsearch

  celery_worker:  # Celery worker 서비스 추가
    build: .
    command: ["sh", "-c", "celery -A han_cycle.app worker -l info"]
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - elasticsearch

  celery_beat:  # Celery beat 서비스 추가(자동화 API요청_날씨)
    build: .
    command: ["sh", "-c", "celery -A han_cycle.app beat -l info"]
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - elasticsearch
      
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
          #celery 브로커
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # 보안을 비활성화
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  postgres_data:
  es_data:
 