# Generated by Django 5.0.7 on 2024-07-29 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_nickname_alter_user_username"),
        ("users", "0003_alter_user_username"),
    ]

    operations = []
