# Generated by Django 4.2.14 on 2024-07-26 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0002_alter_article_published_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Article",
        ),
    ]
