# Generated by Django 5.0.7 on 2024-07-26 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="L_Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "location_id",
                    models.IntegerField(
                        choices=[
                            (1, "서울"),
                            (2, "경기도"),
                            (3, "인천"),
                            (4, "강원도"),
                            (5, "경상북도"),
                            (6, "경상남도"),
                            (7, "대구"),
                            (8, "울산"),
                            (9, "부산"),
                            (10, "충청북도"),
                            (11, "충청남도"),
                            (12, "세종"),
                            (13, "대전"),
                            (14, "전라북도"),
                            (15, "전라남도"),
                            (16, "광주"),
                            (17, "제주도"),
                        ],
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("popular_cities", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("highlights", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="LocationImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField()),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="locations.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "L_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.l_category",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.location",
                    ),
                ),
            ],
            options={
                "unique_together": {("location", "L_category")},
            },
        ),
    ]
