# Generated by Django 4.2.14 on 2024-07-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_categories_remove_l_category_name_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Categories",
        ),
        migrations.AddField(
            model_name="l_category",
            name="name",
            field=models.CharField(
                default="Default Category Name", max_length=100, unique=True
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="LocationCategoryName",
        ),
    ]
