# Generated by Django 4.2.14 on 2024-07-29 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0005_alter_locationcategory_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="L_category",
            new_name="l_category",
        ),
    ]
