# Generated by Django 5.0.7 on 2024-07-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("travel_start_date", models.DateField(blank=True, null=True)),
                ("travel_end_date", models.DateField(blank=True, null=True)),
                ("likes", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
