# Generated by Django 5.0.7 on 2024-07-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("tag", models.CharField(max_length=200)),
                ("region", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("travel_start_date", models.DateField(blank=True, null=True)),
                ("travel_end_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Board",
        ),
    ]
