# Generated by Django 5.0.7 on 2024-07-22 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="is_representative",
        ),
    ]
