# Generated by Django 4.2.14 on 2024-07-29 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("boards", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.location",
            ),
        ),
    ]
