# Generated by Django 5.0.7 on 2024-07-22 14:57

import boards.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0002_remove_image_is_representative"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to=boards.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(upload_to=boards.models.image_upload_path),
        ),
    ]
