# Generated by Django 4.2.14 on 2024-07-29 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0006_rename_l_category_location_l_category"),
        ("boards", "0003_post_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="location",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="locations.location",
            ),
            preserve_default=False,
        ),
    ]
