# Generated by Django 5.0.7 on 2024-07-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0003_alter_image_image_alter_post_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="region",
            field=models.IntegerField(default=0),
        ),
    ]
