# Generated by Django 5.0.7 on 2024-07-24 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0005_post_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
    ]
