# Generated by Django 4.2.14 on 2024-07-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0005_remove_post_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tag",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
