# Generated by Django 5.0.7 on 2024-07-26 06:44

import boards.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0007_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to=boards.models.image_upload_path
            ),
        ),
    ]
